apiVersion: skaffold/v3
kind: Config
metadata:
  name: eoc
build:
  artifacts:
    - image: radiantone/eoc-ui
      context: ./src/cloudmanager-ui
      docker:
          dockerfile: Dockerfile
    - image: radiantone/eoc-backend
      context: ./src/cloudmanager-backend
      docker:
          dockerfile: Dockerfile
    - image: radiantone/eoc-orchestrator
      context: ./src/cloudmanager-environment-orchestrator
      docker:
          dockerfile: Dockerfile
  local:
    useBuildkit: false
manifests:
  rawYaml:
    - "./kubernetes/eoc-ui.yaml"
    - "./kubernetes/eoc-backend.yaml"
    - "./kubernetes/eoc-orchestrator.yaml"
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: eoc-ui-service
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: eoc-backend-service
    port: 80
    localPort: 3001
  - resourceType: service
    resourceName: haproxy
    port: 80
    localPort: 3002