apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: radiantone/eoc-ui
      context: ./src/cloudmanager-ui
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
    - image: radiantone/eoc-backend
      context: ./src/cloudmanager-backend
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
    - image: radiantone/eoc-orchestrator
      context: ./src/cloudmanager-environment-orchestrator
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
deploy:
  helm:
    releases:
      - name: eoc-ui
        chartPath: ./helm/eoc-ui
        artifactOverrides: 
          eoc-ui.image: radiantone/eoc-ui
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_radiantone_eoc_ui}}"
          image.tag: "{{.IMAGE_TAG_radiantone_eoc_ui}}"
      - name: eoc-backend
        chartPath: ./helm/eoc-backend
        artifactOverrides: 
          eoc-backend.image: radiantone/eoc-backend
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_radiantone_eoc_backend}}"
          image.tag: "{{.IMAGE_TAG_radiantone_eoc_backend}}"
      - name: eoc-orchestrator
        chartPath: ./helm/eoc-orchestrator
        artifactOverrides: 
          eoc-orchestrator.image: radiantone/eoc-orchestrator
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_radiantone_eoc_orchestrator}}"
          image.tag: "{{.IMAGE_TAG_radiantone_eoc_orchestrator}}"
  # kubectl:
  #   # defaultNamespace: svc
  #   manifests:
  #     - "./kubernetes/eoc-ui.yaml"
  #     - "./kubernetes/eoc-backend.yaml"
  #     - "./kubernetes/eoc-orchestrator.yaml"
portForward:
  - resourceType: service
    resourceName: eoc-ui-service
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: eoc-backend-service
    port: 80
    localPort: 3001