apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: radiantone/eoc-ui
      context: ./src/cloudmanager-ui
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
    - image: radiantone/eoc-backend
      context: ./src/cloudmanager-backend
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
    - image: radiantone/eoc-orchestrator
      context: ./src/cloudmanager-environment-orchestrator
      docker:
          dockerfile: Dockerfile
      sync:
        infer:
            - "*.js"
            - "*.html"
            - "**/*.js"
deploy:
  # statusCheckDeadlineSeconds: 1
  # helm:
  #   releases:
  #     - name: eoc-all
  #       chartPath: ./helm
  #       artifactOverrides: 
  #         eoc-ui.image: radiantone/eoc-ui
  #         eoc-backend.image: radiantone/eoc-backend
  #         eoc-orchestrator.image: radiantone/eoc-orchestrator
  #       setValueTemplates:
  #         image.ui.repository: "{{.IMAGE_REPO_radiantone_eoc_ui}}"
  #         image.ui.tag: "{{.IMAGE_TAG_radiantone_eoc_ui}}"
  #         image.backend.repository: "{{.IMAGE_REPO_radiantone_eoc_backend}}"
  #         image.backend.tag: "{{.IMAGE_TAG_radiantone_eoc_backend}}"
  #         image.orchestrator.repository: "{{.IMAGE_REPO_radiantone_eoc_orchestrator}}"
  #         image.orchestrator.tag: "{{.IMAGE_TAG_radiantone_eoc_orchestrator}}"
  #       skipBuildDependencies: true
  kubectl:
    # defaultNamespace: svc
    manifests:
      - "./kubernetes/eoc-ui.yaml"
      - "./kubernetes/eoc-backend.yaml"
      - "./kubernetes/eoc-orchestrator.yaml"
portForward:
  - resourceType: service
    resourceName: eoc-ui-service
    # port: 80
    port: 80
    localPort: 3000
  - resourceType: service
    resourceName: eoc-backend-service
    port: 80
    localPort: 3001
  - resourceType: service
    resourceName: haproxy
    port: 80
    localPort: 3002