{{- if .Values.onlyDependencies }}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-ui.fullname" . }}
  labels:
    {{- include "eoc-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-ui.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-ui.selectorLabels" . | nindent 8 }}   
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-ui.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-backend.fullname" . }}
  labels:
    {{- include "eoc-backend.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-backend.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-backend.selectorLabels" . | nindent 8 }}   
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-backend.fullname" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-orchestrator.fullname" . }}
  labels:
    {{- include "eoc-orchestrator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-orchestrator.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-orchestrator.selectorLabels" . | nindent 8 }}   
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-orchestrator.fullname" . }}
{{- end }}