apiVersion: v1
data:
  REDIS_HOST: {{ .Values.orchestrator.redis.host | quote }}
  REDIS_PORT: {{ .Values.orchestrator.redis.port | quote }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-orchestrator
  name: {{ template "eoc-orchestrator.fullname" . }}
  labels:
    app: {{ template "eoc-orchestrator.fullname" . }}
    chart: "{{ template "eoc-orchestrator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"