apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-ui.fullname" . }}
  labels:
    {{- include "eoc-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-ui.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-ui.selectorLabels" . | nindent 8 }}   
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-ui.fullname" . }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}