apiVersion: v1
kind: Service
metadata:
  name: {{ include "eoc-ui.fullname" . }}-service
spec:
  ports:
    - name: {{ include "eoc-ui.fullname" . }}-service-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    {{- include "eoc-ui.selectorLabels" . | nindent 4 }}