apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-ui.fullname" . }}
  labels:
    {{- include "eoc-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-ui.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-ui.selectorLabels" . | nindent 8 }}   
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
