# Default values for fid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: radiantone/eoc-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

eoc-ui:
  VITE_TOKEN_STORE_KEY: "token"
  VITE_BASE_URL: "http://127.0.0.1:3001"
  VITE_LOGIN_URL: "http://127.0.0.1:3000/login"